ALTER TABLE `operations` ADD `exporter_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `exporter_tax_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `internal_responsible` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `responsible_email` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `contract_number` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `incoterm` text DEFAULT 'FOB' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `currency` text DEFAULT 'USD' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `commercial_value` real DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `quantity` real DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `quantity_unit` text DEFAULT 'MT' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `gross_weight_kg` real DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `net_weight_kg` real DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `volume_m3` real DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `lot_codes` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `raw_material` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `species` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `forest_origin_type` text DEFAULT 'Plantação' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `production_unit` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `production_location` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `transport_mode` text DEFAULT 'Marítimo' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `port_of_loading` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `port_of_discharge` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `carrier` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `booking_number` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `container_numbers` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `vessel_voyage` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `eu_operator_eori` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `eudr_reference` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `operations` ADD `supply_chain_notes` text DEFAULT '' NOT NULL;