import { drizzle } from "drizzle-orm/d1";
import * as schema from "./schema";

export async function getDb() {
  const { env } = await import("cloudflare:workers");
  if (!env.DB) {
    throw new Error(
      "Cloudflare D1 binding `DB` is unavailable. Set the `d1` field in .openai/hosting.json to `DB` or let your control plane inject the real binding values before using the database."
    );
  }

  return drizzle(env.DB, { schema });
}

let baseReady: Promise<unknown> | null = null;

export async function ensureBaseTables() {
  if (baseReady) return baseReady;
  const { env } = await import("cloudflare:workers");
  if (!env.DB) throw new Error("Cloudflare D1 binding `DB` is unavailable.");
  baseReady = (async () => {
    try {
      await env.DB.prepare("SELECT (SELECT id FROM suppliers LIMIT 1) AS supplier_id, (SELECT car_code FROM rural_properties LIMIT 1) AS property_id").first();
      return;
    } catch {
      // A instalação inicial ainda não possui as tabelas; execute o bootstrap legado uma única vez.
    }
    await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS suppliers (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      legal_name text NOT NULL,
      trade_name text DEFAULT '' NOT NULL,
      tax_id text NOT NULL,
      country text DEFAULT 'Brasil' NOT NULL,
      state text NOT NULL,
      city text NOT NULL,
      contact_name text NOT NULL,
      email text NOT NULL,
      phone text DEFAULT '' NOT NULL,
      certifications text DEFAULT 'Sem certificação' NOT NULL,
      aliases text DEFAULT '' NOT NULL,
      products text DEFAULT '' NOT NULL,
      production_units text DEFAULT '' NOT NULL,
      bank_details text DEFAULT '' NOT NULL,
      status text DEFAULT 'Homologado' NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    env.DB.prepare("CREATE UNIQUE INDEX IF NOT EXISTS suppliers_org_tax_id_idx ON suppliers (organization_id,tax_id)"),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS operations (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      reference text DEFAULT '' NOT NULL UNIQUE,
      product text DEFAULT 'A classificar' NOT NULL,
      hs_code text DEFAULT '' NOT NULL,
      destination_country text DEFAULT '' NOT NULL,
      eu_importer text DEFAULT '' NOT NULL,
      importer_client_id integer,
      master_product_id integer,
      supplier_id integer,
      supplier_name text NOT NULL,
      shipment_date text DEFAULT '' NOT NULL,
      exporter_name text DEFAULT '' NOT NULL,
      exporter_tax_id text DEFAULT '' NOT NULL,
      internal_responsible text DEFAULT '' NOT NULL,
      responsible_email text DEFAULT '' NOT NULL,
      contract_number text DEFAULT '' NOT NULL,
      incoterm text DEFAULT 'FOB' NOT NULL,
      currency text DEFAULT 'USD' NOT NULL,
      commercial_value real DEFAULT 0 NOT NULL,
      quantity real DEFAULT 0 NOT NULL,
      quantity_unit text DEFAULT 'MT' NOT NULL,
      gross_weight_kg real DEFAULT 0 NOT NULL,
      net_weight_kg real DEFAULT 0 NOT NULL,
      volume_m3 real DEFAULT 0 NOT NULL,
      lot_codes text DEFAULT '' NOT NULL,
      raw_material text DEFAULT '' NOT NULL,
      species text DEFAULT '' NOT NULL,
      forest_origin_type text DEFAULT 'Plantação' NOT NULL,
      production_unit text DEFAULT '' NOT NULL,
      production_location text DEFAULT '' NOT NULL,
      property_ids text DEFAULT '[]' NOT NULL,
      transport_mode text DEFAULT 'Marítimo' NOT NULL,
      port_of_loading text DEFAULT '' NOT NULL,
      port_of_discharge text DEFAULT '' NOT NULL,
      carrier text DEFAULT '' NOT NULL,
      booking_number text DEFAULT '' NOT NULL,
      container_numbers text DEFAULT '' NOT NULL,
      vessel_voyage text DEFAULT '' NOT NULL,
      eu_operator_eori text DEFAULT '' NOT NULL,
      eudr_reference text DEFAULT '' NOT NULL,
      supply_chain_notes text DEFAULT '' NOT NULL,
      readiness integer DEFAULT 10 NOT NULL,
      status text DEFAULT 'Cadastro inicial' NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS operation_documents (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      operation_id integer NOT NULL,
      category text NOT NULL,
      file_name text NOT NULL,
      object_key text NOT NULL UNIQUE,
      content_type text DEFAULT 'application/octet-stream' NOT NULL,
      size_bytes integer NOT NULL,
      status text DEFAULT 'Recebido' NOT NULL,
      notes text DEFAULT '' NOT NULL,
      source_system text DEFAULT 'Upload manual' NOT NULL,
      source_external_id text DEFAULT '' NOT NULL,
      source_task_id text DEFAULT '' NOT NULL,
      source_created_at text DEFAULT '' NOT NULL,
      document_type text DEFAULT 'Outro documento' NOT NULL,
      lifecycle_status text DEFAULT 'Vigente' NOT NULL,
      shipment_set_status text DEFAULT 'Fora do set' NOT NULL,
      client_share_status text DEFAULT 'Interno' NOT NULL,
      analysis_summary text DEFAULT '' NOT NULL,
      sha256 text DEFAULT '' NOT NULL,
      uploaded_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS forest_documents (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      property_car_code text NOT NULL,
      category text NOT NULL,
      file_name text NOT NULL,
      object_key text NOT NULL UNIQUE,
      content_type text DEFAULT 'application/octet-stream' NOT NULL,
      size_bytes integer NOT NULL,
      notes text DEFAULT '' NOT NULL,
      source text DEFAULT 'Fornecido pelo responsável' NOT NULL,
      uploaded_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (property_car_code) REFERENCES rural_properties(car_code)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS operation_stage_settings (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      operation_id integer NOT NULL,
      stage_category text NOT NULL,
      enabled integer DEFAULT 1 NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id),
      UNIQUE(operation_id, stage_category)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS operation_partners (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      operation_id integer NOT NULL,
      role text NOT NULL,
      company_name text NOT NULL,
      contact_name text DEFAULT '' NOT NULL,
      email text DEFAULT '' NOT NULL,
      country text DEFAULT 'Brasil' NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS exception_actions (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      alert_text text NOT NULL,
      operation_reference text DEFAULT 'GBU002/26' NOT NULL,
      responsible_name text NOT NULL,
      responsible_email text NOT NULL,
      due_date text NOT NULL,
      message text NOT NULL,
      status text DEFAULT 'Notificado' NOT NULL,
      notified_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      resolved_at text,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS industrial_plans (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      operation_id integer NOT NULL UNIQUE,
      period_start text NOT NULL,
      period_end text NOT NULL,
      receiving_lots text DEFAULT '' NOT NULL,
      opening_stock_kg real DEFAULT 0 NOT NULL,
      raw_material_received_kg real DEFAULT 0 NOT NULL,
      raw_material_consumed_kg real DEFAULT 0 NOT NULL,
      pellets_produced_kg real DEFAULT 0 NOT NULL,
      closing_stock_kg real DEFAULT 0 NOT NULL,
      production_lots text DEFAULT '' NOT NULL,
      notes text DEFAULT '' NOT NULL,
      status text DEFAULT 'Em elaboração' NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_services (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      agent_id text NOT NULL UNIQUE,
      service_id text NOT NULL UNIQUE,
      name text NOT NULL,
      description text NOT NULL,
      capabilities_json text DEFAULT '[]' NOT NULL,
      category text NOT NULL,
      provider text NOT NULL,
      adapter_type text DEFAULT 'internal' NOT NULL,
      endpoint text DEFAULT 'internal://local' NOT NULL,
      internal integer DEFAULT 1 NOT NULL,
      price real DEFAULT 0 NOT NULL,
      currency text DEFAULT 'USD' NOT NULL,
      estimated_cost real DEFAULT 0 NOT NULL,
      average_response_ms integer DEFAULT 1000 NOT NULL,
      availability real DEFAULT 100 NOT NULL,
      reputation real DEFAULT 80 NOT NULL,
      execution_count integer DEFAULT 0 NOT NULL,
      success_rate real DEFAULT 100 NOT NULL,
      last_used_at text,
      status text DEFAULT 'Ativo' NOT NULL,
      financial_limit real DEFAULT 25 NOT NULL,
      requires_human_approval integer DEFAULT 1 NOT NULL,
      commercial integer DEFAULT 0 NOT NULL,
      input_description text DEFAULT '' NOT NULL,
      output_description text DEFAULT '' NOT NULL,
      sla text DEFAULT '' NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_operation_settings (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      operation_id integer NOT NULL UNIQUE,
      autonomy_level integer DEFAULT 1 NOT NULL,
      transaction_limit real DEFAULT 25 NOT NULL,
      daily_limit real DEFAULT 100 NOT NULL,
      external_payments_enabled integer DEFAULT 0 NOT NULL,
      allowed_providers_json text DEFAULT '[]' NOT NULL,
      blocked_providers_json text DEFAULT '[]' NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_jobs (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      job_id text NOT NULL UNIQUE,
      operation_id integer NOT NULL,
      stage_category text NOT NULL,
      requesting_agent text DEFAULT 'supply-chain-orchestrator' NOT NULL,
      provider_agent text NOT NULL,
      capability text NOT NULL,
      input_json text DEFAULT '{}' NOT NULL,
      document_ids_json text DEFAULT '[]' NOT NULL,
      candidate_scores_json text DEFAULT '[]' NOT NULL,
      expected_price real DEFAULT 0 NOT NULL,
      actual_price real DEFAULT 0 NOT NULL,
      currency text DEFAULT 'USD' NOT NULL,
      status text DEFAULT 'Aguardando aprovação' NOT NULL,
      result text DEFAULT '' NOT NULL,
      confidence real DEFAULT 0 NOT NULL,
      duration_ms integer DEFAULT 0 NOT NULL,
      error text DEFAULT '' NOT NULL,
      approval_status text DEFAULT 'Pendente' NOT NULL,
      approved_by text DEFAULT '' NOT NULL,
      approved_at text,
      logs_json text DEFAULT '[]' NOT NULL,
      output_document_json text DEFAULT '{}' NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      completed_at text,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_ledger (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      job_id text NOT NULL,
      operation_id integer NOT NULL,
      client_name text DEFAULT '' NOT NULL,
      stage_category text NOT NULL,
      agent_id text NOT NULL,
      service_id text NOT NULL,
      entry_type text NOT NULL,
      amount real DEFAULT 0 NOT NULL,
      currency text DEFAULT 'USD' NOT NULL,
      description text DEFAULT '' NOT NULL,
      simulated integer DEFAULT 1 NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_reputation (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      agent_id text NOT NULL,
      capability text NOT NULL,
      success_count integer DEFAULT 0 NOT NULL,
      failure_count integer DEFAULT 0 NOT NULL,
      average_duration_ms integer DEFAULT 0 NOT NULL,
      quality_score real DEFAULT 80 NOT NULL,
      average_cost_variance_pct real DEFAULT 0 NOT NULL,
      average_confidence real DEFAULT 0 NOT NULL,
      human_validation_rate real DEFAULT 0 NOT NULL,
      rework_count integer DEFAULT 0 NOT NULL,
      later_divergence_count integer DEFAULT 0 NOT NULL,
      score real DEFAULT 80 NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UNIQUE(agent_id, capability)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS payment_transactions (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      payment_id text NOT NULL UNIQUE,
      operation_id integer,
      job_id text DEFAULT '' NOT NULL,
      provider text NOT NULL,
      method text NOT NULL,
      direction text NOT NULL,
      catalog_key text DEFAULT '' NOT NULL,
      amount real DEFAULT 0 NOT NULL,
      currency text DEFAULT 'BRL' NOT NULL,
      status text DEFAULT 'created' NOT NULL,
      external_reference text DEFAULT '' NOT NULL,
      checkout_url text DEFAULT '' NOT NULL,
      simulated integer DEFAULT 1 NOT NULL,
      metadata_json text DEFAULT '{}' NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      settled_at text,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS export_control_settings (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      operation_id integer NOT NULL UNIQUE,
      customer_name text DEFAULT '' NOT NULL,
      customer_email text DEFAULT '' NOT NULL,
      customer_reference text DEFAULT '' NOT NULL,
      notifications_enabled integer DEFAULT 1 NOT NULL,
      tracking_interval_days integer DEFAULT 10 NOT NULL,
      next_tracking_at text,
      email_provider_status text DEFAULT 'Simulação' NOT NULL,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS export_milestones (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      operation_id integer NOT NULL,
      code text NOT NULL,
      sequence integer NOT NULL,
      title text NOT NULL,
      category text NOT NULL,
      status text DEFAULT 'Pendente' NOT NULL,
      quality_status text DEFAULT 'Não iniciado' NOT NULL,
      shipment_approval text DEFAULT 'Não aplicável' NOT NULL,
      responsible_name text DEFAULT '' NOT NULL,
      responsible_email text DEFAULT '' NOT NULL,
      due_date text DEFAULT '' NOT NULL,
      next_action text DEFAULT '' NOT NULL,
      note text DEFAULT '' NOT NULL,
      completed_at text,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id),
      UNIQUE(operation_id, code)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS client_notifications (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      operation_id integer NOT NULL,
      milestone_code text DEFAULT '' NOT NULL,
      recipient text DEFAULT '' NOT NULL,
      subject text NOT NULL,
      body text NOT NULL,
      status text DEFAULT 'Rascunho' NOT NULL,
      provider text DEFAULT 'simulation' NOT NULL,
      external_id text DEFAULT '' NOT NULL,
      error text DEFAULT '' NOT NULL,
      sent_at text,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS shipment_tracking_events (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      operation_id integer NOT NULL,
      source text DEFAULT 'manual' NOT NULL,
      status text NOT NULL,
      location text DEFAULT '' NOT NULL,
      eta text DEFAULT '' NOT NULL,
      details text DEFAULT '' NOT NULL,
      checked_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      next_check_at text DEFAULT '' NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS shipment_advices (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      operation_id integer NOT NULL,
      status text DEFAULT 'Rascunho' NOT NULL,
      recipient text DEFAULT '' NOT NULL,
      subject text DEFAULT '' NOT NULL,
      body text DEFAULT '' NOT NULL,
      payment_request text DEFAULT 'Solicitar pagamento do saldo e comprovante SWIFT.' NOT NULL,
      document_ids_json text DEFAULT '[]' NOT NULL,
      checklist_json text DEFAULT '[]' NOT NULL,
      human_approved integer DEFAULT 0 NOT NULL,
      approved_by text DEFAULT '' NOT NULL,
      approved_at text,
      sent_at text,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id),
      UNIQUE(organization_id, operation_id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS country_compliance_checks (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      operation_id integer NOT NULL,
      country text NOT NULL,
      hs_code text NOT NULL,
      score integer DEFAULT 0 NOT NULL,
      status text DEFAULT 'Pendente' NOT NULL,
      result_json text DEFAULT '[]' NOT NULL,
      checked_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (operation_id) REFERENCES operations(id)
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS asana_import_candidates (
      id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      organization_id integer DEFAULT 1 NOT NULL,
      source_project_id text NOT NULL,
      source_project_name text DEFAULT 'VLP EXPORTAÇÃO' NOT NULL,
      task_gid text NOT NULL,
      parent_task_gid text DEFAULT '' NOT NULL,
      name text NOT NULL,
      section_name text DEFAULT '' NOT NULL,
      assignee_name text DEFAULT '' NOT NULL,
      assignee_email text DEFAULT '' NOT NULL,
      due_date text DEFAULT '' NOT NULL,
      completed integer DEFAULT 0 NOT NULL,
      source_status text DEFAULT '' NOT NULL,
      notes text DEFAULT '' NOT NULL,
      source_url text DEFAULT '' NOT NULL,
      modified_at text DEFAULT '' NOT NULL,
      proposed_milestone_code text DEFAULT '' NOT NULL,
      attention_reasons_json text DEFAULT '[]' NOT NULL,
      import_status text DEFAULT 'Aguardando revisão' NOT NULL,
      matched_operation_id integer,
      reviewed_at text,
      updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
      FOREIGN KEY (matched_operation_id) REFERENCES operations(id),
      UNIQUE(organization_id, source_project_id, task_gid)
    )`),
    ]);
  })().catch((error: unknown) => {
    baseReady = null;
    throw error;
  });
  return baseReady;
}
