import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const organizations = sqliteTable("organizations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  taxId: text("tax_id").notNull().default(""),
  status: text("status").notNull().default("Ativa"),
  dataRegion: text("data_region").notNull().default("global"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const appUsers = sqliteTable("app_users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  email: text("email").notNull().unique(),
  fullName: text("full_name").notNull().default(""),
  status: text("status").notNull().default("Ativo"),
  identityProvider: text("identity_provider").notNull().default("chatgpt-siwc"),
  lastLoginAt: text("last_login_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const organizationMemberships = sqliteTable("organization_memberships", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  userId: integer("user_id").notNull().references(() => appUsers.id),
  role: text("role").notNull().default("cliente"),
  status: text("status").notNull().default("Ativo"),
  invitedBy: text("invited_by").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("organization_memberships_org_user_idx").on(table.organizationId, table.userId)]);

export const ruralProperties = sqliteTable("rural_properties", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  carCode: text("car_code").notNull().unique(),
  name: text("name").notNull(),
  city: text("city").notNull(),
  supplier: text("supplier").notNull(),
  areaHa: real("area_ha").notNull(),
  nativeAreaHa: real("native_area_ha").notNull().default(0),
  status: text("status").notNull().default("Em análise"),
  risk: text("risk").notNull().default("atenção"),
  geometryJson: text("geometry_json").notNull(),
  sourceFile: text("source_file").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const forestDocuments = sqliteTable("forest_documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  propertyCarCode: text("property_car_code").notNull().references(() => ruralProperties.carCode),
  category: text("category").notNull(),
  fileName: text("file_name").notNull(),
  objectKey: text("object_key").notNull().unique(),
  contentType: text("content_type").notNull().default("application/octet-stream"),
  sizeBytes: integer("size_bytes").notNull(),
  notes: text("notes").notNull().default(""),
  source: text("source").notNull().default("Fornecido pelo responsável"),
  uploadedAt: text("uploaded_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const suppliers = sqliteTable("suppliers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  legalName: text("legal_name").notNull(),
  tradeName: text("trade_name").notNull().default(""),
  taxId: text("tax_id").notNull(),
  country: text("country").notNull().default("Brasil"),
  state: text("state").notNull(),
  city: text("city").notNull(),
  contactName: text("contact_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull().default(""),
  certifications: text("certifications").notNull().default("Sem certificação"),
  aliases: text("aliases").notNull().default(""),
  products: text("products").notNull().default(""),
  productionUnits: text("production_units").notNull().default(""),
  bankDetails: text("bank_details").notNull().default(""),
  status: text("status").notNull().default("Homologado"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("suppliers_org_tax_id_idx").on(table.organizationId, table.taxId),
]);

export const productTraceabilityCatalog = sqliteTable("product_traceability_catalog", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  product: text("product").notNull(),
  entryType: text("entry_type").notNull(),
  value: text("value").notNull(),
  scientificName: text("scientific_name").notNull().default(""),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("product_traceability_catalog_org_product_type_value_idx").on(table.organizationId, table.product, table.entryType, table.value),
]);

export const importerClients = sqliteTable("importer_clients", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  legalName: text("legal_name").notNull(),
  normalizedName: text("normalized_name").notNull(),
  aliases: text("aliases").notNull().default(""),
  taxId: text("tax_id").notNull().default(""),
  taxIdType: text("tax_id_type").notNull().default("VAT"),
  eori: text("eori").notNull().default(""),
  address: text("address").notNull().default(""),
  city: text("city").notNull().default(""),
  state: text("state").notNull().default(""),
  postalCode: text("postal_code").notNull().default(""),
  country: text("country").notNull(),
  contactName: text("contact_name").notNull().default(""),
  email: text("email").notNull().default(""),
  phone: text("phone").notNull().default(""),
  preferredPort: text("preferred_port").notNull().default(""),
  paymentTerms: text("payment_terms").notNull().default(""),
  documentRequirements: text("document_requirements").notNull().default(""),
  dataStatus: text("data_status").notNull().default("Pendente"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("importer_clients_org_normalized_idx").on(table.organizationId, table.normalizedName)]);

export const masterProducts = sqliteTable("master_products", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  name: text("name").notNull(),
  normalizedName: text("normalized_name").notNull(),
  rawMaterial: text("raw_material").notNull().default(""),
  species: text("species").notNull().default(""),
  scientificName: text("scientific_name").notNull().default(""),
  hsCode: text("hs_code").notNull().default(""),
  dimensionalSpecification: text("dimensional_specification").notNull().default(""),
  grade: text("grade").notNull().default(""),
  kd: integer("kd", { mode: "boolean" }).notNull().default(false),
  ht: integer("ht", { mode: "boolean" }).notNull().default(false),
  moisture: text("moisture").notNull().default(""),
  certifications: text("certifications").notNull().default(""),
  originType: text("origin_type").notNull().default("Reflorestamento"),
  eligibleSupplierIds: text("eligible_supplier_ids").notNull().default("[]"),
  dataStatus: text("data_status").notNull().default("Pendente"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("master_products_org_normalized_idx").on(table.organizationId, table.normalizedName)]);

export const deduplicationQueue = sqliteTable("deduplication_queue", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  entityType: text("entity_type").notNull(),
  primaryRecordId: integer("primary_record_id").notNull(),
  possibleDuplicateId: integer("possible_duplicate_id").notNull(),
  reason: text("reason").notNull(),
  confidence: real("confidence").notNull().default(0),
  status: text("status").notNull().default("Possível duplicidade"),
  resolutionNote: text("resolution_note").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("dedupe_queue_unique_pair_idx").on(table.organizationId, table.entityType, table.primaryRecordId, table.possibleDuplicateId)]);

export const operations = sqliteTable("operations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  reference: text("reference").notNull().unique(),
  product: text("product").notNull(),
  hsCode: text("hs_code").notNull(),
  destinationCountry: text("destination_country").notNull(),
  euImporter: text("eu_importer").notNull(),
  importerClientId: integer("importer_client_id").references(() => importerClients.id),
  masterProductId: integer("master_product_id").references(() => masterProducts.id),
  supplierId: integer("supplier_id").references(() => suppliers.id),
  supplierName: text("supplier_name").notNull(),
  shipmentDate: text("shipment_date").notNull().default(""),
  exporterName: text("exporter_name").notNull().default(""),
  exporterTaxId: text("exporter_tax_id").notNull().default(""),
  internalResponsible: text("internal_responsible").notNull().default(""),
  responsibleEmail: text("responsible_email").notNull().default(""),
  contractNumber: text("contract_number").notNull().default(""),
  incoterm: text("incoterm").notNull().default("FOB"),
  currency: text("currency").notNull().default("USD"),
  commercialValue: real("commercial_value").notNull().default(0),
  quantity: real("quantity").notNull().default(0),
  quantityUnit: text("quantity_unit").notNull().default("MT"),
  grossWeightKg: real("gross_weight_kg").notNull().default(0),
  netWeightKg: real("net_weight_kg").notNull().default(0),
  volumeM3: real("volume_m3").notNull().default(0),
  lotCodes: text("lot_codes").notNull().default(""),
  rawMaterial: text("raw_material").notNull().default(""),
  species: text("species").notNull().default(""),
  forestOriginType: text("forest_origin_type").notNull().default("Plantação"),
  productionUnit: text("production_unit").notNull().default(""),
  productionLocation: text("production_location").notNull().default(""),
  propertyIds: text("property_ids").notNull().default("[]"),
  transportMode: text("transport_mode").notNull().default("Marítimo"),
  portOfLoading: text("port_of_loading").notNull().default(""),
  portOfDischarge: text("port_of_discharge").notNull().default(""),
  carrier: text("carrier").notNull().default(""),
  bookingNumber: text("booking_number").notNull().default(""),
  billOfLadingNumber: text("bill_of_lading_number").notNull().default(""),
  containerNumbers: text("container_numbers").notNull().default(""),
  vesselVoyage: text("vessel_voyage").notNull().default(""),
  euOperatorEori: text("eu_operator_eori").notNull().default(""),
  eudrReference: text("eudr_reference").notNull().default(""),
  supplyChainNotes: text("supply_chain_notes").notNull().default(""),
  readiness: integer("readiness").notNull().default(10),
  status: text("status").notNull().default("Cadastro inicial"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const operationDocuments = sqliteTable("operation_documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  category: text("category").notNull(),
  fileName: text("file_name").notNull(),
  objectKey: text("object_key").notNull().unique(),
  contentType: text("content_type").notNull().default("application/octet-stream"),
  sizeBytes: integer("size_bytes").notNull(),
  status: text("status").notNull().default("Recebido"),
  notes: text("notes").notNull().default(""),
  sourceSystem: text("source_system").notNull().default("Upload manual"),
  sourceExternalId: text("source_external_id").notNull().default(""),
  sourceTaskId: text("source_task_id").notNull().default(""),
  sourceCreatedAt: text("source_created_at").notNull().default(""),
  documentType: text("document_type").notNull().default("Outro documento"),
  lifecycleStatus: text("lifecycle_status").notNull().default("Vigente"),
  shipmentSetStatus: text("shipment_set_status").notNull().default("Fora do set"),
  clientShareStatus: text("client_share_status").notNull().default("Interno"),
  analysisSummary: text("analysis_summary").notNull().default(""),
  sha256: text("sha256").notNull().default(""),
  uploadedAt: text("uploaded_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const operationStageSettings = sqliteTable("operation_stage_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  stageCategory: text("stage_category").notNull(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("operation_stage_settings_operation_stage_idx").on(table.operationId, table.stageCategory),
]);

export const operationPartners = sqliteTable("operation_partners", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  role: text("role").notNull(),
  companyName: text("company_name").notNull(),
  contactName: text("contact_name").notNull().default(""),
  email: text("email").notNull().default(""),
  country: text("country").notNull().default("Brasil"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const exceptionActions = sqliteTable("exception_actions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  alertText: text("alert_text").notNull(),
  operationReference: text("operation_reference").notNull().default("GBU002/26"),
  responsibleName: text("responsible_name").notNull(),
  responsibleEmail: text("responsible_email").notNull(),
  dueDate: text("due_date").notNull(),
  message: text("message").notNull(),
  status: text("status").notNull().default("Notificado"),
  notifiedAt: text("notified_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  resolvedAt: text("resolved_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const industrialPlans = sqliteTable("industrial_plans", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().unique().references(() => operations.id),
  periodStart: text("period_start").notNull(),
  periodEnd: text("period_end").notNull(),
  receivingLots: text("receiving_lots").notNull().default(""),
  openingStockKg: real("opening_stock_kg").notNull().default(0),
  rawMaterialReceivedKg: real("raw_material_received_kg").notNull().default(0),
  rawMaterialConsumedKg: real("raw_material_consumed_kg").notNull().default(0),
  pelletsProducedKg: real("pellets_produced_kg").notNull().default(0),
  closingStockKg: real("closing_stock_kg").notNull().default(0),
  productionLots: text("production_lots").notNull().default(""),
  notes: text("notes").notNull().default(""),
  status: text("status").notNull().default("Em elaboração"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agentServices = sqliteTable("agent_services", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  agentId: text("agent_id").notNull().unique(),
  serviceId: text("service_id").notNull().unique(),
  name: text("name").notNull(),
  description: text("description").notNull(),
  capabilitiesJson: text("capabilities_json").notNull().default("[]"),
  category: text("category").notNull(),
  provider: text("provider").notNull(),
  adapterType: text("adapter_type").notNull().default("internal"),
  endpoint: text("endpoint").notNull().default("internal://local"),
  internal: integer("internal", { mode: "boolean" }).notNull().default(true),
  price: real("price").notNull().default(0),
  currency: text("currency").notNull().default("USD"),
  estimatedCost: real("estimated_cost").notNull().default(0),
  averageResponseMs: integer("average_response_ms").notNull().default(1000),
  availability: real("availability").notNull().default(100),
  reputation: real("reputation").notNull().default(80),
  executionCount: integer("execution_count").notNull().default(0),
  successRate: real("success_rate").notNull().default(100),
  lastUsedAt: text("last_used_at"),
  status: text("status").notNull().default("Ativo"),
  financialLimit: real("financial_limit").notNull().default(25),
  requiresHumanApproval: integer("requires_human_approval", { mode: "boolean" }).notNull().default(true),
  commercial: integer("commercial", { mode: "boolean" }).notNull().default(false),
  inputDescription: text("input_description").notNull().default(""),
  outputDescription: text("output_description").notNull().default(""),
  sla: text("sla").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agentOperationSettings = sqliteTable("agent_operation_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  operationId: integer("operation_id").notNull().unique().references(() => operations.id),
  autonomyLevel: integer("autonomy_level").notNull().default(1),
  transactionLimit: real("transaction_limit").notNull().default(25),
  dailyLimit: real("daily_limit").notNull().default(100),
  externalPaymentsEnabled: integer("external_payments_enabled", { mode: "boolean" }).notNull().default(false),
  allowedProvidersJson: text("allowed_providers_json").notNull().default("[]"),
  blockedProvidersJson: text("blocked_providers_json").notNull().default("[]"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agentJobs = sqliteTable("agent_jobs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  jobId: text("job_id").notNull().unique(),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  stageCategory: text("stage_category").notNull(),
  requestingAgent: text("requesting_agent").notNull().default("supply-chain-orchestrator"),
  providerAgent: text("provider_agent").notNull(),
  capability: text("capability").notNull(),
  inputJson: text("input_json").notNull().default("{}"),
  documentIdsJson: text("document_ids_json").notNull().default("[]"),
  candidateScoresJson: text("candidate_scores_json").notNull().default("[]"),
  expectedPrice: real("expected_price").notNull().default(0),
  actualPrice: real("actual_price").notNull().default(0),
  currency: text("currency").notNull().default("USD"),
  status: text("status").notNull().default("Aguardando aprovação"),
  result: text("result").notNull().default(""),
  confidence: real("confidence").notNull().default(0),
  durationMs: integer("duration_ms").notNull().default(0),
  error: text("error").notNull().default(""),
  approvalStatus: text("approval_status").notNull().default("Pendente"),
  approvedBy: text("approved_by").notNull().default(""),
  approvedAt: text("approved_at"),
  logsJson: text("logs_json").notNull().default("[]"),
  outputDocumentJson: text("output_document_json").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
});

export const agentLedger = sqliteTable("agent_ledger", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  jobId: text("job_id").notNull(),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  clientName: text("client_name").notNull().default(""),
  stageCategory: text("stage_category").notNull(),
  agentId: text("agent_id").notNull(),
  serviceId: text("service_id").notNull(),
  entryType: text("entry_type").notNull(),
  amount: real("amount").notNull().default(0),
  currency: text("currency").notNull().default("USD"),
  description: text("description").notNull().default(""),
  simulated: integer("simulated", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agentReputation = sqliteTable("agent_reputation", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  agentId: text("agent_id").notNull(),
  capability: text("capability").notNull(),
  successCount: integer("success_count").notNull().default(0),
  failureCount: integer("failure_count").notNull().default(0),
  averageDurationMs: integer("average_duration_ms").notNull().default(0),
  qualityScore: real("quality_score").notNull().default(80),
  averageCostVariancePct: real("average_cost_variance_pct").notNull().default(0),
  averageConfidence: real("average_confidence").notNull().default(0),
  humanValidationRate: real("human_validation_rate").notNull().default(0),
  reworkCount: integer("rework_count").notNull().default(0),
  laterDivergenceCount: integer("later_divergence_count").notNull().default(0),
  score: real("score").notNull().default(80),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("agent_reputation_agent_capability_idx").on(table.agentId, table.capability),
]);

export const agentCredentials = sqliteTable("agent_credentials", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  credentialId: text("credential_id").notNull().unique(),
  name: text("name").notNull().default("Agente Particular"),
  tokenHash: text("token_hash").notNull(),
  scopesJson: text("scopes_json").notNull().default("[]"),
  status: text("status").notNull().default("Ativo"),
  lastFour: text("last_four").notNull().default(""),
  expiresAt: text("expires_at"),
  revokedAt: text("revoked_at"),
  lastUsedAt: text("last_used_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("agent_credentials_org_credential_idx").on(table.organizationId, table.credentialId),
]);

export const agentEvents = sqliteTable("agent_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  eventId: text("event_id").notNull(),
  source: text("source").notNull(),
  externalId: text("external_id").notNull().default(""),
  subject: text("subject").notNull().default(""),
  sender: text("sender").notNull().default(""),
  recipientsJson: text("recipients_json").notNull().default("[]"),
  summary: text("summary").notNull().default(""),
  payloadJson: text("payload_json").notNull().default("{}"),
  matchedOperationId: integer("matched_operation_id").references(() => operations.id),
  matchConfidence: text("match_confidence").notNull().default("NONE"),
  matchScore: real("match_score").notNull().default(0),
  status: text("status").notNull().default("Recebido"),
  error: text("error").notNull().default(""),
  processedAt: text("processed_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("agent_events_org_event_idx").on(table.organizationId, table.eventId),
]);

export const operationTimeline = sqliteTable("operation_timeline", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  eventType: text("event_type").notNull().default("agent_event"),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  source: text("source").notNull().default("agent"),
  externalEventId: text("external_event_id").notNull().default(""),
  documentId: integer("document_id").references(() => operationDocuments.id),
  metadataJson: text("metadata_json").notNull().default("{}"),
  createdBy: text("created_by").notNull().default("Agente Particular"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agentApprovals = sqliteTable("agent_approvals", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  approvalId: text("approval_id").notNull().unique(),
  actionType: text("action_type").notNull(),
  operationId: integer("operation_id").references(() => operations.id),
  description: text("description").notNull(),
  proposedActionJson: text("proposed_action_json").notNull().default("{}"),
  currentDataJson: text("current_data_json").notNull().default("{}"),
  proposedDataJson: text("proposed_data_json").notNull().default("{}"),
  risk: text("risk").notNull().default("MEDIUM"),
  requestedBy: text("requested_by").notNull().default("Agente Particular"),
  requestedAt: text("requested_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  status: text("status").notNull().default("PENDING"),
  decidedBy: text("decided_by").notNull().default(""),
  decidedAt: text("decided_at"),
  decisionNote: text("decision_note").notNull().default(""),
  expiresAt: text("expires_at"),
}, (table) => [
  uniqueIndex("agent_approvals_org_approval_idx").on(table.organizationId, table.approvalId),
]);

export const paymentTransactions = sqliteTable("payment_transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  paymentId: text("payment_id").notNull().unique(),
  operationId: integer("operation_id").references(() => operations.id),
  jobId: text("job_id").notNull().default(""),
  provider: text("provider").notNull(),
  method: text("method").notNull(),
  direction: text("direction").notNull(),
  catalogKey: text("catalog_key").notNull().default(""),
  amount: real("amount").notNull().default(0),
  currency: text("currency").notNull().default("BRL"),
  status: text("status").notNull().default("created"),
  externalReference: text("external_reference").notNull().default(""),
  checkoutUrl: text("checkout_url").notNull().default(""),
  simulated: integer("simulated", { mode: "boolean" }).notNull().default(true),
  metadataJson: text("metadata_json").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  settledAt: text("settled_at"),
});

export const exportControlSettings = sqliteTable("export_control_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().unique().references(() => operations.id),
  customerName: text("customer_name").notNull().default(""),
  customerEmail: text("customer_email").notNull().default(""),
  customerReference: text("customer_reference").notNull().default(""),
  notificationsEnabled: integer("notifications_enabled", { mode: "boolean" }).notNull().default(true),
  trackingIntervalDays: integer("tracking_interval_days").notNull().default(10),
  nextTrackingAt: text("next_tracking_at"),
  emailProviderStatus: text("email_provider_status").notNull().default("Simulação"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const exportMilestones = sqliteTable("export_milestones", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  code: text("code").notNull(),
  sequence: integer("sequence").notNull(),
  title: text("title").notNull(),
  category: text("category").notNull(),
  status: text("status").notNull().default("Pendente"),
  qualityStatus: text("quality_status").notNull().default("Não iniciado"),
  shipmentApproval: text("shipment_approval").notNull().default("Não aplicável"),
  responsibleName: text("responsible_name").notNull().default(""),
  responsibleEmail: text("responsible_email").notNull().default(""),
  dueDate: text("due_date").notNull().default(""),
  nextAction: text("next_action").notNull().default(""),
  note: text("note").notNull().default(""),
  completedAt: text("completed_at"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("export_milestones_operation_code_idx").on(table.operationId, table.code)]);

export const clientNotifications = sqliteTable("client_notifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  milestoneCode: text("milestone_code").notNull().default(""),
  recipient: text("recipient").notNull().default(""),
  subject: text("subject").notNull(),
  body: text("body").notNull(),
  status: text("status").notNull().default("Rascunho"),
  provider: text("provider").notNull().default("simulation"),
  externalId: text("external_id").notNull().default(""),
  error: text("error").notNull().default(""),
  sentAt: text("sent_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const shipmentAdvices = sqliteTable("shipment_advices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  status: text("status").notNull().default("Rascunho"),
  recipient: text("recipient").notNull().default(""),
  subject: text("subject").notNull().default(""),
  body: text("body").notNull().default(""),
  paymentRequest: text("payment_request").notNull().default("Solicitar pagamento do saldo e comprovante SWIFT."),
  documentIdsJson: text("document_ids_json").notNull().default("[]"),
  checklistJson: text("checklist_json").notNull().default("[]"),
  humanApproved: integer("human_approved", { mode: "boolean" }).notNull().default(false),
  approvedBy: text("approved_by").notNull().default(""),
  approvedAt: text("approved_at"),
  sentAt: text("sent_at"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("shipment_advices_org_operation_idx").on(table.organizationId, table.operationId)]);

export const shipmentTrackingEvents = sqliteTable("shipment_tracking_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  source: text("source").notNull().default("manual"),
  status: text("status").notNull(),
  location: text("location").notNull().default(""),
  eta: text("eta").notNull().default(""),
  details: text("details").notNull().default(""),
  checkedAt: text("checked_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  nextCheckAt: text("next_check_at").notNull().default(""),
});

export const countryComplianceChecks = sqliteTable("country_compliance_checks", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  operationId: integer("operation_id").notNull().references(() => operations.id),
  country: text("country").notNull(),
  hsCode: text("hs_code").notNull(),
  score: integer("score").notNull().default(0),
  status: text("status").notNull().default("Pendente"),
  resultJson: text("result_json").notNull().default("[]"),
  checkedAt: text("checked_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const asanaImportCandidates = sqliteTable("asana_import_candidates", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().default(1),
  sourceProjectId: text("source_project_id").notNull(),
  sourceProjectName: text("source_project_name").notNull().default("VLP EXPORTAÇÃO"),
  taskGid: text("task_gid").notNull(),
  parentTaskGid: text("parent_task_gid").notNull().default(""),
  name: text("name").notNull(),
  sectionName: text("section_name").notNull().default(""),
  assigneeName: text("assignee_name").notNull().default(""),
  assigneeEmail: text("assignee_email").notNull().default(""),
  dueDate: text("due_date").notNull().default(""),
  completed: integer("completed", { mode: "boolean" }).notNull().default(false),
  sourceStatus: text("source_status").notNull().default(""),
  notes: text("notes").notNull().default(""),
  sourceUrl: text("source_url").notNull().default(""),
  modifiedAt: text("modified_at").notNull().default(""),
  proposedMilestoneCode: text("proposed_milestone_code").notNull().default(""),
  attentionReasonsJson: text("attention_reasons_json").notNull().default("[]"),
  importStatus: text("import_status").notNull().default("Aguardando revisão"),
  matchedOperationId: integer("matched_operation_id").references(() => operations.id),
  reviewedAt: text("reviewed_at"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("asana_import_candidates_org_project_task_idx").on(table.organizationId, table.sourceProjectId, table.taskGid),
]);

export const auditLogs = sqliteTable("audit_logs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  actorUserId: integer("actor_user_id").references(() => appUsers.id),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull().default(""),
  metadataJson: text("metadata_json").notNull().default("{}"),
  previousHash: text("previous_hash").notNull().default("GENESIS"),
  eventHash: text("event_hash").notNull().unique(),
  requestId: text("request_id").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const documentAccessTokens = sqliteTable("document_access_tokens", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  tokenHash: text("token_hash").notNull().unique(),
  documentType: text("document_type").notNull(),
  documentId: integer("document_id").notNull(),
  inline: integer("inline", { mode: "boolean" }).notNull().default(false),
  createdBy: text("created_by").notNull(),
  expiresAt: text("expires_at").notNull(),
  usedAt: text("used_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const backupSnapshots = sqliteTable("backup_snapshots", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  objectKey: text("object_key").notNull().unique(),
  contentHash: text("content_hash").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  status: text("status").notNull().default("Concluído"),
  triggeredBy: text("triggered_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const pdfIntegrityRecords = sqliteTable("pdf_integrity_records", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  operationId: integer("operation_id").references(() => operations.id),
  propertyCarCode: text("property_car_code").notNull().default(""),
  documentType: text("document_type").notNull(),
  fileName: text("file_name").notNull(),
  sha256: text("sha256").notNull(),
  generatedBy: text("generated_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const legalAcceptances = sqliteTable("legal_acceptances", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  userId: integer("user_id").notNull().references(() => appUsers.id),
  documentType: text("document_type").notNull(),
  version: text("version").notNull(),
  acceptedAt: text("accepted_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("legal_acceptances_user_doc_version_idx").on(table.userId, table.documentType, table.version)]);

export const systemEvents = sqliteTable("system_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  level: text("level").notNull().default("error"),
  source: text("source").notNull(),
  fingerprint: text("fingerprint").notNull(),
  message: text("message").notNull(),
  metadataJson: text("metadata_json").notNull().default("{}"),
  status: text("status").notNull().default("Aberto"),
  occurredAt: text("occurred_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  resolvedAt: text("resolved_at"),
});

export const gmailConnections = sqliteTable("gmail_connections", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  userId: integer("user_id").notNull().references(() => appUsers.id),
  gmailAddress: text("gmail_address").notNull().default(""),
  accessTokenEncrypted: text("access_token_encrypted").notNull().default(""),
  refreshTokenEncrypted: text("refresh_token_encrypted").notNull().default(""),
  accessTokenExpiresAt: text("access_token_expires_at"),
  scopesJson: text("scopes_json").notNull().default("[]"),
  historyId: text("history_id").notNull().default(""),
  status: text("status").notNull().default("Ativo"),
  lastSyncAt: text("last_sync_at"),
  lastError: text("last_error").notNull().default(""),
  connectedAt: text("connected_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("gmail_connections_org_user_idx").on(table.organizationId, table.userId)]);

export const googleOauthStates = sqliteTable("google_oauth_states", {
  stateHash: text("state_hash").primaryKey(),
  organizationId: integer("organization_id").notNull().references(() => organizations.id),
  userId: integer("user_id").notNull().references(() => appUsers.id),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
